### ISSUE TITLE
UseIdentityServerBearerTokenAuthentication add Bearer token to the Response header?

### ISSUE THREAD

**Issue by mikeandersun** [IdentityServer/Thinktecture.IdentityServer3#1053]
I have an angular app that is host in a MVC web site and call a web api from angular app:
The Web Api return 200(OK) until 5 minutes. 
but after 5 minutes it return 401(Unauthorized) and the response have "WWW-Authenticate:Bearer"  header with empty token. This is my config for web api 
 app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
            {
                Authority =options.AuthorityServer
            }

I expected WWW-Authenticate:Bearer [thetoken].
Am i right? if so how i can get token?

Thanks for your helps.

**Comment by iltera** [comment]
How are you getting the access_token from your Angular app?
Are you using the TokenManager function in the oidc.js file which is in the samples or manually sending a request to the idsrv host to get the access_token?

I'm using the TokenManager in the angular's run function, in order not to create multiple samples of the TokenManager across the app. Run method in Angular runs only the first time when the application is bootstrapped. As far as I observed that is the only suitable place to create the TokenManager and let run there for the entire application lifetime.

When you create an instance of the TokenManager, let's say, to a "mgr" variable, you can say "mgr.redirectForToken();" if the "mgr.expired" is true. The TokenManager will renew the token for you on the last 60th second, automatically. Check the JSAuth sample in the [Samples](https://github.com/IdentityServer/Thinktecture.IdentityServer3.Samples/tree/master/source/OAuthJS/JsImplicitOAuthLibraryDemo) project.

I also had some issues during mu trials. You can find the issue #1047.

**Comment by leastprivilege** [comment]
No - the response header does not have the token. Just the scheme.

**Comment by mikeandersun** [comment]
@iltera thanks for replay. I want to get access_token in via a MVC authorized controller action and add in to request header via an inspector in angular app. 
Am in a right way?
Thanks

**Comment by iltera** [comment]
When using .net MVC, you have the chance to use Hybrid Flow, which allows you to continue getting access tokens by using a refresh token. If you weren't using AngularJS, then I would suggest you to get down that road. In hybrid flow you make the calls to WebApi from server side methods. You have to create calls to the Api with a specialized method which adds headers to the requests (only for Api requests). That flow (hybrid) requires you to register your client_id and secret. That way, you're combining the Implicit Flow with Authorization Flow and that is called Hybrid Flow. You see, as we need to register the client id and secret, we have to use that on server side.

But in a js application, like an AngularJS app, we don't use client id and secret. Actually, we can't use them at all for security. In Single Page Applications (SPA), all code is run in client's browser. That means all you codes are accessible. Even if you bundle and minify your js files, that client id and secret will be there in plaintext for anyone curious to see. And client secret is called a secret for a reason. You can't share it! That is why the hybrid or authorization code flows are not suitable for a SPA. So, there is the Implicit Flow that you should follow for the JS SPAs.

You asked me a two line question but get a page response, that's because when you told me that you're trying to get the access token from server side and use it in client side, I thought may be you need some clearification on the flows you should use. I've been in your shoes a few weeks ago, trying to get the id_token and access_token from server side and save it to a cookie and then use it from angular and so on... I then found out that the iodc.js file in the OAuthJS Sample project has all a SPA needs in order to get tokens and to refresh tokens (runs a function to silently renew the token if the validity of the token is less than 60 secs.) from an iframe running in the background. That seemed like a better fit to me. That is, of course if you're not receiving any sensitive information from mvc controllers. Because as far as I learned till now, when using SPA and WebApi's all you do is securing the WebApi. You don't secure the templates of your applicaiton but your data. That's the way I went and wanted to share my limited knowledge with you.

And a side note. Be careful if you decide to implement Hybrid on MVC and Implicit Flow on the SPA which is running on that MVC app. Things may seem to be running normal at first, but as soon as the token lifetimes begin to end, you start getting really wierd errors from both sides because you have many tokens from many sources and it's not only the tokens, there is state, nonce values that are created and used when tokens are issued. These all get pretty messed up before you know it.

Hope that helps.

**Comment by mikeandersun** [comment]
Thanks a lot @iltera for sharing your experiences and your time to give me a page answer to a line question :).
 I am a new to the JS environment and A&A. 
Is it good approach to get access token within MVC and send it to ng-app? OR 
Using Implicit Flow in MVC and ng-app? OR 
 Implement Hybrid on MVC and Implicit Flow on the SPA which is running on that MVC app?(with careful)

I find you :)
Thanks a lot again

**Comment by iltera** [comment]
As you read in my previous answer, I just shared my experiences with you. May be it's all right to obtain the access token from MVC and send it somehow to js application and use it there. But, I would rather use MVC just for setting the Angular $locationProvider's html5mode option to true. That removes the # tag from url of your application. Other than that, I wouldn't include security in anyway to the MVC side. Even AngularJS docs implies that mixing server side templates and client side templates is a very bad idea. People often use SPAs like AngularJS in combination with WebApi. That doesn't even require the existance of MVC in the proccess.

As for the taking tokens from the server and using in SPA, I had many problems with it and gave up eventually. Believe me, it's a lot easier to use TokenManager in oidc.js file then going through the path you seek. I recommend you to follow some courses in PluralSight, as they helped me a lot. Especially a recently released one [Building and Securing a RESTful API for Multiple Clients in ASP.NET](http://www.pluralsight.com/courses/building-securing-restful-api-aspdotnet). That course explain all about securing API with IdentityServer3 and the OIDC Flows at once.

Good luck ;)

**Comment by pessimca** [comment]
I am also facing same issue my WebAPI and Angular JS. application is working good but it will start failing when app is idle for sometime. I verified access_token (bearer) on request header and it is there and no change. I tried same scenario on postman with access_token and getting same issue.

Please share your suggestions if anyone has same issues and fixed.

Thank you.
