### ISSUE TITLE
Rework logging everywhere

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/Thinktecture.IdentityServer3#588]

**Comment by dcjulian29** [comment]
I'd like to +1 this issue... I'm having a terrible time troubleshooting some "unexpected error" on a hosting server while it works on my local system. Just created an issue on the documentation issue tracker though that may have been to wrong place to create it... If I can not resolve the "generic" log-in error soon, I'll have to abandon (IMHO) a superior authentication/authorization solution and return to an internal (most likely insecure) authentication solution...

**Comment by leastprivilege** [comment]
Tracing works fine and is actually very detailed. The docs are up to date. 

You need to trace to a location on the file system where the worker process has write access to.

**Comment by dcjulian29** [comment]
I meant no disrespect... but at the same time, this isn't my first rodeo. :)  I had set up tracing using a blog post I found on your website by adding the following to my web.config:
```xml
     <system.diagnostics>
        <trace autoflush="true">
            <listeners>
                <add name="AuthenticationServer_QA_Listener" />
            </listeners>
        </trace>
        <sources>
            <source name="Thinktecture.IdentityModel">
                <listeners>
                    <add name="AuthenticationServer_QA_Listener" />
                </listeners>
            </source>
        </sources>
        <sharedListeners>
            <add name="AuthenticationServer_QA_Listener"
                 type="System.Diagnostics.XmlWriterTraceListener"
                 initializeData="C:\tracing\authentication_web_qa.svclog"
                 traceOutputOptions="Callstack">
                <filter type="" />
            </add>
        </sharedListeners>
    </system.diagnostics>
```
I gave the "EVERYONE" security principal full control to the `C:\tracing` directory. At this point I didn't get any tracing files... I even added a `Trace.Write("test");` to verify that I had the configuration/permissions correct... Doing this did output the trace file... but I still got nothing from `Thinktecture.IdentityModel` source...

It wasn't until I thought to add the `EnableWebApiDiagnostics = true` to the `IdentityServerOptions` in the Startup.cs file. Doing that finally started the flow of tracing information and I was able to see that I'd stupidly forgot to give the AppPool identity permission to the private key of the certificate... So after much gnashing of teeth, I was able to track down the issue and get the identity server authenticating my WebApi users...

 I looked at the documentation at: http://thinktecture.github.io/Thinktecture.IdentityServer.v3.Documentation/docs/configuration/logging.html today and find that it is very detailed. It does have a section on "Configuring Diagnostics" but it does not connect the two together...  I'll have to circle back to that and look much closer at this page so that I can enable the logging portion in the code to connect it to our logging provider (Common.Logging).

**Comment by brockallen** [comment]
That looks like IdentityServer v2 logging config, not IdentityServer v3 logging... so perhaps you're at the wrong rodeo. Here are the logging docs:

https://thinktecture.github.io/Thinktecture.IdentityServer.v3.Documentation/docs/configuration/logging.html

**Comment by dcjulian29** [comment]
Wouldn't be the first time I ended up at the wrong rodeo...  ;)  FYI, your link to the documentation is the same as the link in my post...  Regardless, with the `Thinktecture.IdentityServer.v3.1.0.0-beta4` NuGet package and the configuration above, tracing works and outputs a lot of information... Just listened to your DotNetRocks episode this morning so I'm looking forward to the "final" release of Identity Server so that you can work on Identity Manager.  Having deployed a version 2 server last year, I miss not having the web interface for user and role management in version 3...
