### ISSUE TITLE
OpenID Connect, OAuth2 and User Details Syncronization

### ISSUE THREAD

**Issue by jlegan** [IdentityServer/Thinktecture.IdentityServer3#811]
Bit of a cross post at SO: http://stackoverflow.com/questions/28116711/openid-connect-oauth2-and-user-details-syncronization

I have created a OpenID Connect / Authorization server based in large part on IdentityServer V3 from Thinktecture. For the sake of simplicity assume that this entire platform consists of the following:

 - An ASP.NET Web API hosting IdentityServer v3 and exposing controllers to manage the ASP.NET Identity implementation that Idv3 is using for OpenID Connect. We will call this the AuthServer.
 - Two additional resource servers, also ASP.NET web API, we can call them API1 and API2.
 - Total of 3 AngularJS based implicit clients, one each to work with the API's (AuthServer management front end, API1 front end and API2 front end).

There are several other clients out there (mobile apps, etc...) but they are not pertinent to the question.

When a new user attempts to register on the platform, either from the front end of API1 or API2, they are walked through a wizard on the Angular front end and during the process a user is created through the AuthServer API (ASP.NET Identity). At this point in time the user is authenticated through AuthServer and they have both a token and id_token and can successfully use the services through the front end for which ever API they registered for.

The difficulty I have having is two fold:

 1. Where would you generally store user details? The AuthServer needs at the very least an email address (email address validation and lost password) as well as a first name and last name to make communications more personal. The API in question (API1 or API2) require various details about the user (address, date of birth, etc...) and due to this variability it does not make sense to store them in the identity server. I am leaning towards storing the initially registered values for First, Last and Email in both places and then only allow updates in the front end for the apps (API1 and API2) and make those apps responsible for updating the AuthServer via a client credential flow. Does this make the most sense?
 2. I am using UseIdentityServerBearerTokenAuthentication which is a wrapper for UseOAuthBearerAuthentication in my OWIN pipeline. I am able to successfully authorize the user, validate my claims, etc... However I am having difficulty determining how to get the issuing authority out of the context successfully and determining where the correct place is in the pipeline to call the userinfo end point in order to retrieve user details from the AuthServer. I can do it at the controller level, injecting a user details service into it but I would really like to do this at a higher level and append the details to the users identity so that if the app requires some specific details about the user each and every time it is called, the API can call the AuthServer to retrieve them. This is very straight forward in the UseOpenIdConnectAuthentication MVC implementation as they have eventing that allows for direct access to the authentication ticket. Is there a "correct" way to do this?

**Comment by johnkors** [comment]
First, not sure why you would have to duplicate where your user data. Common user data should be stored centrally and available through your IUserService imo. To be more precise, common user data like the claims specified in the Spec (Profile, Email, ++) I would store in whatever userdb your idsrv instance is talking to. More app specific data for a specific domain would be stored within that client apps persistance store.

No expert, but I think I would make the user details needed for doing API calls a requirement (must be included in the access_token) to use the APIs. So for instance, if a user wants to use your API that requires address, make the user fill out address in a "Edit Profile" page (prompted partial login) before letting them use that part of your client application. Otherwise, your API would need to call the UserInfoEndpoint at every request. Which could be fine, but I personally find that this approach is more overhead for your API (more http). Also, for the API to fetch the Address data from the userinfo endpoint, it would need an access_token with the address scope itself (in the scenario where the access_token sent from the client did not include the address scope). Then the API would have to become another client, instead of just having to validate incoming tokens.

I think. :)

**Comment by jlegan** [comment]
John,

What about reporting? Keep in mind that these are applications, not strictly API's. While this is not the vertical market in question, I will use real estate as the example.

From a strictly design speaking perspective, I agree I would love to keep everything that is necessary for all apps behind idv3 however running a simple database query, generating a mailing list for one of the apps instantly becomes a problem. I would no longer be able to write queries against my repositories to generate any data that contained first, last, email, company, etc... without making http calls and reporting occurs around the clock.

My initial thoughts were that during user registration, a POST would be made to both the app API and the idv3 API (exposing the user service for asp.net identity) and then during an edit of the profile from within the app, update those details in both places as well to keep them in sync.\

This is why I was leaning towards a more lean implementation in identity (first, last, middle initial, email, MFA) and nothing more but I was not sure if I was missing something obvious.
 
Thanks for your help.

Jim
