### ISSUE TITLE
adding custom controllers to extend functionality

### ISSUE THREAD

**Issue by stevenfirstrowinc** [IdentityServer/Thinktecture.IdentityServer3#812]
This isn't exactly an IdSrv issue but is it possible (and if so how) to add custom API controllers to allow the functionality to be extended?  For instance if I wanted to allow someone to query users by a role claim and resource.  I know it's a bit outside of the scope of idsrv but I appreciate your thoughts.

**Comment by brockallen** [comment]
I'd suggest building an API that accepts tokens from IdSvr to authenticate the calls. Your API then access the same DB that IdSvr is using for users. Look at how IdMgr is doing it.

**Comment by RainerBasso** [comment]
Actually this is already possible. Let's say you have a controller like this:

public class MyApiController : ApiController
{
        [HttpGet]
        [Route("my/api/hello")]
        public string Get()
        {
            return "hello";
        }
}

You can register it like this:

factory.Register(Registration.RegisterType<MyApiController>(typeof(MyApiController)));

and it will be resolved and called by the IdSrv when address matches.

I was trying to do what Brock is suggesting but  I was unable to get it working under the same domain.

**Comment by RainerBasso** [comment]
I just noted that github removed the type in my comment in the line:

factory.Register(Registration.RegisterType<MyApiController>(typeof(MyApiController)));

be aware.

**Comment by brockallen** [comment]
We have a way to add custom controllers, but it's undocumented, current unsupported, and not really done. Look at the WS-Fed repo for an example.

**Comment by stevenfirstrowinc** [comment]
Do you mean this one?
https://github.com/IdentityServer/Thinktecture.IdentityServer3.WsFederation

or one of the samples here? 
https://github.com/IdentityServer/Thinktecture.IdentityServer3.Samples

**Comment by brockallen** [comment]
The first one.

**Comment by ChrisVinall** [comment]
Just wondering if anything has changed since this was closed. I want to inject a single ApiController into IdentityServer. I had a look at the WsFederation plugin but it seems very heavy duty for what I'm trying to do. I'm not very familiar with Autofac and hoped this would work:

idSvrFactory.Register(new Registration<AccountManagementController>("AccountManagementController"));

It doesn't seem to do anything, though.

Would you be amenable to the idea of exposing access to Autofac's RegisterApiControllers in the idsrv factory?

**Comment by brockallen** [comment]
The design of IdSvr doesn't allow outside code to inject Web API semantics -- nothing in IdSvr would know to invoke it.

**Comment by ChrisVinall** [comment]
OK... maybe it would help if I explained what I'm trying to do.

I'm trying to implement partial logins, as in the CustomUserService samples - redirecting to a custom controller after the login. I need to remain within the idsrv Owin context in order to validate the partial login. CustomUserService achieves this by mapping routes using the System.Web MVC pipeline. I'd like to use an ApiController and stay as a pure Owin app, but idsrv doesn't (appear to) allow me to map routes in the usual manner. Any way I can achieve what I'm trying to do?

Many thanks.

**Comment by brockallen** [comment]
You can do that. Requests come into OWIN and get mapped to your URLs (outside of IdSvr's space). IOW, the routing/mapping is not from within IdSvr, but at the OWIN level. For URLs into IdSvr, you'd let those travel into IdSvr normally.

**Comment by ChrisVinall** [comment]
I'm attempting to do this by mapping my own app with the routing I need, but then in my controller when I call await ctx.Authentication.AuthenticateAsync(Constants.PartialSignInAuthenticationType) it returns null.

[Giist here](https://gist.github.com/ChrisVinall/be3730a4e2d92664764d) with the relevant code. Am I doing something wrong?

**Comment by ChrisVinall** [comment]
I can't use attribute routing because of [#917](https://github.com/IdentityServer/Thinktecture.IdentityServer3/pull/917).

**Comment by ChrisVinall** [comment]
I manually reverted #917 so my controllers are discoverable and it works fine now with attribute routing. If there's a method of setting up routing to Web API that I'm not aware of (as in other than via HttpConfiguration or attribute routing) then I'd appreciate being pointed in that direction. For now I'm going to proceed with my slightly modified Core.

**Comment by leastprivilege** [comment]
You really need a separate Web API host instead of adding your controllers to our host. Nasty side effects waiting to happen..

**Comment by ChrisVinall** [comment]
Such as? Not that I don't believe you, just wondering :)

All the stuff I'm adding is related to the authentication process (signup form, demanding a mobile number from external logins that don't provide one, etc). I'm not even certain how it would work if I had a Web API secured by identity server - it redirects them to there to enter a mobile number, but then when they try to log in there it redirects them again because they don't have a mobile number, etc? It seems like a central authentication server ought to be the place for these tasks.

**Comment by leastprivilege** [comment]
What I don't get is - why does it need to be the same physical instance of Web API host. You can still host any number of endpoints in the same app - but in your own host.

**Comment by ChrisVinall** [comment]
I feel like there's something basic I'm not understanding here...

Brock's suggestion at top of page is to use a Web API with token security. That's a non-starter for me because I'm trying to do things in the midst of partial login. I can't issue a token yet.

So then I look into trying to verify the partial login outside the context of idsrv core. The docs have this to say:

"In order to obtain these claims, the page must use the Katana authentication middleware to authenticate against the Constants.PartialSignInAuthenticationType authentication type, or simply be executing within the same cookie path as IdentityServer on the web server."

OK, so first I find out that the cookie path is set as /core. That's fine, I can change that in options to be /. But then I run into this guy:

TicketDataFormat = new TicketDataFormat(new DataProtectorAdapter(dataProtector, options.Prefix + Constants.PartialSignInAuthenticationType))

This I can't change in options. If I comment this line out, it works. I've tried replicating the machinery that does the encryption, but it fails for whatever reason.

It seems like the docs say I need to verify the partial login cookie, but I've been locked out of doing so. What am I missing?

**Comment by leastprivilege** [comment]
Check the custom user service sample (the one with registration) - that seems to me very similar to what you try to accomplish.

**Comment by ChrisVinall** [comment]
That brings me full circle to this:

>I'm trying to implement partial logins, as in the CustomUserService samples - redirecting to a custom controller after the login. I need to remain within the idsrv Owin context in order to validate the partial login. CustomUserService achieves this by mapping routes using the System.Web MVC pipeline. I'd like to use an ApiController and stay as a pure Owin app, but idsrv doesn't (appear to) allow me to map routes in the usual manner.

I have it working though. It turned out when I replicated the TicketDataFormat that idsrv uses, the reason it didn't work was stale cookies. It's a bit hacky because I've "borrowed" the internal HostDataProtector and DataProtectorAdaptor to use in my assembly. It might be good to expose in CookieOptions a way to use default TicketDataFormat for environments where the entire host server is trusted.

Thanks for the help.

**Comment by plemm98** [comment]
Interesting post.

With the version beta 3 of the identity server, i was able to register my custom api controller by adding the following line in the Core\Configuration\Hosting\AutofacConfig.cs.

            builder.RegisterApiControllers(
                Assembly.Load("Test, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null"));
            builder.RegisterControllers(
                Assembly.Load("Test, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null"));


            // add any additional dependencies from hosting application
            foreach (var registration in fact.Registrations)
            {
                builder.Register(registration);
            }

            var container = builder.Build();
            DependencyResolver.SetResolver(new AutofacDependencyResolver(container));
            return container;

But, it dosen't work with version 1.2 anymore. In the "container" object, i can see my helloworld web api class register in the autofac container object.

But, when i try to communicate with my web api, i receive the not found exception. Not good.

Beside adding my assembly to the autofacconfig.cs file, is there something else i need to do to register my custom web api?

Best regards,

**Comment by ChrisVinall** [comment]
plemm,

Check #917. Idsrv is configured to only map controllers within its own assembly. Here's the code, from WebApiConfig.cs in idsrv core:

    config.Services.Replace(typeof(IHttpControllerTypeResolver), new HttpControllerTypeResolver());

    private class HttpControllerTypeResolver : IHttpControllerTypeResolver
    {
        public ICollection<Type> GetControllerTypes(IAssembliesResolver _)
        {
            var httpControllerType = typeof (IHttpController);
            return typeof (WebApiConfig)
                .Assembly
                .GetTypes()
                .Where(t => t.IsClass && !t.IsAbstract && httpControllerType.IsAssignableFrom(t))
                .ToList();
        }
    }

The normal approach is to map a second app within Startup.cs in your idsrv host which is secured by idsrv as in the SampleWebApi in samples. You can create your own `IHttpControllerTypeResolver` to map only your own controllers (by having them all inherit from a base class, for instance). This is how mine looks:

        app.Map("/custom", customApp =>
        {
            customApp.CreatePerOwinContext(Context.Create);
            customApp.CreatePerOwinContext<UserManager>(UserManager.Create);
            HttpConfiguration httpConfig = new HttpConfiguration();
            httpConfig.Services.Replace(typeof(IHttpControllerTypeResolver), new CustomEndpointsResolver());
            httpConfig.MapHttpAttributeRoutes();
            JwtSecurityTokenHandler.InboundClaimTypeMap = new Dictionary<string, string>();
            customApp.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
            {
                Authority = ConfigurationManager.AppSettings[AppConstants.IssuerUri] + AppConstants.CoreEndpoint,
                RequiredScopes = new[] { "write" }
            });
            customApp.UseWebApi(httpConfig);
        });

I had to do something a bit trickier to add a controller that worked in the middle of a partial login, but the above works for most purposes.

**Comment by plemm98** [comment]
Hi Chris,

Thank you for your input!

It is now working like it suppose to.

I was not aware of this for sure.

Best regards,

**Comment by trezum** [comment]
When i try to use the code pasted by ChrisVinall to host web api besides identityserver and use IdentityServerBearerTokenAuthentication i get the following exception, in the UseIdentityServerBearerTokenAuthentication call of the web api configuration in the owin startup class:
  "_IDX10803: Unable to create to obtain configuration from: 'https://localhost:44333/identity/.well-known/openid-configuration'._"

I am guessing it is becaus the identityserver is not started when the web api asks for the configuration.
Anyone got a surgestion? :)

**Comment by ChrisVinall** [comment]
Usually that means the instance isn't running or your URL/port are wrong. Comment out the custom ApiController stuff and hit the .well-known URL and see what happens.

**Comment by trezum** [comment]
Hey Chris 
Thanks for your respons :) 
When i do this the wellknown works like usual. When i only comment out the UseIdentityServerBearerTokenAuthentication part  the Custom controller type revolver gets hit too, when i access some Custom URL. However i haven't been able to get actual output from a controller yet. Not sure if it could be related? :)

**Comment by trezum** [comment]
My Startup.cs looks like this: 
http://puu.sh/nxV5l/5155822d53.png
Is it really possible to have UseIdentityServerBearerTokenAuthentication connecting to the same owin app, do i need to delay the startup of the web api untill the identityserver is running, or have i missunderstood something? :)

**Comment by leastprivilege** [comment]
there is a DelayLoadMetadata property on the options class.

**Comment by trezum** [comment]
Oh man diden't notice, thanks alot Dominick :)
