### ISSUE TITLE
How to implement  Thinktecture.IdentityServer3 For android application

### ISSUE THREAD

**Issue by RajMondaz** [IdentityServer/Thinktecture.IdentityServer3#869]
Need some reference link..

**Comment by johnkors** [comment]
We do this via a combination of web views in the android app and using the hybrid flow (because we need access tokens). You could use the implicit flow as well, if you don't need access tokens In both cases we use do the fragment response mode. 

Look at the WPF sample in the sample repo to see what is done there and you'll get an idea.

**Comment by RajMondaz** [comment]
Hi,
i need to know is there any sample Identity server 3 application for android app in github
 (like we have identity server samples for mvc ,wpf and angular)

**Comment by leastprivilege** [comment]
no there isn't.

**Comment by RajMondaz** [comment]
ok.

**Comment by RajMondaz** [comment]
can we except identity server implementation (samples) for the android applications in upcoming days.

**Comment by leastprivilege** [comment]
no. unless someone wants to contribute that.

**Comment by atul221282** [comment]
I also want to use hybrid flow rather than resource owner credentials flow but I am using nativescript for my mobile apps and there webview doesn't support callback uri at the moment i think or may be I am not fully aware of that and I am still investigating about it but encase if I cannot use hybrid flow then is it safe to use resource owner flow as this app is fully trusted as dropbox app you have mentioned in ur pluralsight tutorials
