### ISSUE TITLE
Route Sharing / Extended Idv3 Route

### ISSUE THREAD

**Issue by jlegan** [IdentityServer/Thinktecture.IdentityServer3#876]
This may be a limitation of .NET but is there a way to extend the base route that Idv3 is initialized with? 

Many of the examples use /identity or /core and from a clean implementation standpoint I would want to reuse this base path for other controllers, extending API's such as user registration (i.e. .../identity/user/registration) exposed through my own likely attribute routed controllers.

I have tried using both attribute routing as well as traditional routing and neither hit controllers when using the same root as Idv3.

**Comment by johnkors** [comment]
That's because of the ```app.Map("/core", a => a.SomeMw())``` isolates this path to that middleware. I guess you could either 

1) put it at root by removing the .Map 
or 
2) Use something that supports running as a Owin MW, like Nancy.

```
app.Map("/core", a => { app.UseIdsrv(); app.UseNancy(); });
```

We tried option 1, and got into lots of issues re System.Web (ASP.NET MVC) and Katana fighting over cookies. So I would investigate option 2 if I were to do it again..

**Comment by jlegan** [comment]
Thank you John, I was already looking into Nancy as a possible solution.
