### ISSUE TITLE
Store access_token for multiple use

### ISSUE THREAD

**Issue by sandeepgaikwad** [IdentityServer/Thinktecture.IdentityServer3#890]
I am using Identity server 3 to authenticate/authorize MVC apps and web api's.
I have secured web api's which are called from the mvc app's different parts.

In order to hit the webapi securely I request an access_token from the Identity server using OAuth2Client (client.RequestClientCredentialsAsync). I can use the token returned from the IdP to access web api.
During login I do not request the access_token, rather I prefer to get the token whenever my application needs to communicate with a backend service.

But my question is: I have scenarios where my web api will be hit several times, I don't think advisable to get the access_token for each call/hit. What I want is to store the access_token after first hit and reuse it. What is the best practice to achieve this? Can I put the access_token in ClaimsPrincipal? Is this feasible/ advisable?
Is there a out of box technique for this?or do I just need use ViewBag/Viewdata mechanisms?

Thanks in advance

**Comment by brockallen** [comment]
Just reuse the access_token -- it can be used until it expires (which is a configuration setting in IdSvr).

**Comment by RaulMo7** [comment]
U can store tokens in database for reuse, using Identity Server Entity Framework.

 var options = new EntityFrameworkServiceOptions
            {
                ConnectionString = "databaseidsrv3"
            };

            factory.RegisterConfigurationServices(options);
            factory.RegisterOperationalServices(options);

Grettings.

**Comment by brockallen** [comment]
@RaulMo7 i think @sandeepgaikwad meant from the client side application. But yes, if you're doing reference tokens, refresh tokens, or need to remember consent, you will need a DB in the server (at least for production), as @RaulMo7 points out.

**Comment by jlegan** [comment]
Brock,

On that subject for my own education, what is the preferred (if any) storage mechanism on the client side or even service to service? Shared cache? It was one of the items I was going to tackle next week (MVC app talking to Web API (implicit or hybrid) and WebAPI to WebAPI (client creds). On the intra service communication side of things (webapi to web api), since I will be hosting in Azure and will scale to demand I was leaning towards a distributed cache solution like redis and storing a hashed version of the token that the consumer could retrieve and expire the cache before the token expires to in order to retrieve the next token before caching it.

The MVC one will simply be pulled from the identity of the logged in user. The renewing of the client token is something I have not investigated yet but I was leaning towards hybrid flow and thus refresh tokens.

**Comment by brockallen** [comment]
You can put the access token in the user's cookie as a claim.

**Comment by jlegan** [comment]
I am doing that for the MVC -> WebAPI case but what about the client credentials flow case (intraservice webapi -> webapi)?

**Comment by brockallen** [comment]
Just is an in-memory variable.

**Comment by jlegan** [comment]
Understood. The reason I was leaning towards a caching solutions was due to the scaling. If I scale to 10 instances running of a web or worker role in Azure, I would tend to lean towards not having 10 live tokens (one being stored in memory on each role) but it would certainly work. Thank you for the input! Looking forward to building off of this platform and hopefully contributing to it as I go along.

**Comment by brockallen** [comment]
Sure, that could work as well.

**Comment by sandeepgaikwad** [comment]
My apologies, I could not work on this today.
I'll comment on the use of access_token after I try it out tomorrow

**Comment by sandeepgaikwad** [comment]
Sorry for delay from my end, was stuck up with some other work.
Brock: My use case is little different, let me explain:
I have a frontfacing MVC app and several web api's serving up the MVC app.
In MVC app, I use following during authentication ,in the app.UseOpenIdConnectAuthentication pipeline:
ResponseType = "id_token token",
Scope = "openid "

Note: Here I don't request the access_token for my web api(s)

Once authenticated, whenever the MVC app needs talk with the background api, I request for accesstoken for corresponding api, as follows:
 var client = new OAuth2Client(new Uri(BaseAddress + "/connect/token), "{webapiname}", "{secretkey}");
return client.RequestClientCredentialsAsync("access_token").Result;

Here I get the token for the corresponding api (there could be another place in the application which may ask for token for same api or a different api, which may have different name and secret)
Once I have the accesstoken, I use it as follows:
using (HttpClient httpClient = new HttpClient())
            {
                httpClient.SetBearerToken(response.AccessToken);
                jsonResponse = httpClient.GetStringAsync(url).Result;

            }

Now my question is: This same api may be called several times during a session, how can I reuse it? Is there a built-in support for this, or do I have to use ViewBag or similar session storing mechanism?

**Comment by brockallen** [comment]
So you're doing client credentials flow. I don't see why you don't request all the scopes in one round-trip to the token endpoint, since it's essentially the same one client accessing all of them. And then once it has the token, store it in-memory global to the app for re-use until it expires.

**Comment by sandeepgaikwad** [comment]
Yes, i think that's best approach
Thanks
