### ISSUE TITLE
Access Token Validation & Caching Problem

### ISSUE THREAD

**Issue by jlegan** [IdentityServer/Thinktecture.IdentityServer3#946]
I implemented Redis caching last week using the UseIdentityServerBearerTokenAuthentication middleware. I did a quick test and confirmed that the cache was working (token and claims were successfully pushed into cache, confirmed with a redis CLI client. I then moved onto a different part of the project and started troubleshooting a 401 being thrown by an API controller on the second attempt to call it from the MVC client. I had verbose logging on and it was not making sense so I set some break points in my cache implementation and I once again confirmed that it was working as expected (cache is checked and is added). However, every subsequent attempt to call the API fails with a 401 and the cache is never touched (get or set). If I set EnableValidationResultCache to false in the middleware and make it go to the database every time it works successfully each and every time. Below is my implementation of both the middleware and cache. Can anyone see what might be tripping this up on a second request? To summarize:

* Cache is populated successfully on the first attempt to use an access token (reference tokens are being used).
* Cache has an expiry of 5 minutes (confirmed that it is being cleaned up properly).
* Two calls made back to back (same controller, same reference token, same API) fails with a 401 after the first successful call that added it to the cache.
* On the subsequent requests, the breakpoints in the cache are never hit and I receive an immediate 401, happening software in the Owin pipeline.
* Turning off cache in the middleware allows everything to work successfully.

**Update:** I converted the client over to using straight access tokens instead of reference tokens and the behavior persists.

````
app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
            {
                Authority = CloudConfigurationManager.GetSetting("TokenAuthority"),
                RequiredScopes = new[] {Scopes.Lockdown.Management},
                RoleClaimType = Claims.Role,
                AuthenticationMode = AuthenticationMode.Active,
                ValidationMode = ValidationMode.ValidationEndpoint,
                EnableValidationResultCache = true, 
                ValidationResultCacheDuration = TimeSpan.FromMinutes(Convert.ToInt32(CloudConfigurationManager.GetSetting("TokenCacheDuration"))),
                ValidationResultCache =
                    new RedisValidationResultCache(Convert.ToInt32(CloudConfigurationManager.GetSetting("TokenCacheDuration")),
                        ConnectionMultiplexer.Connect(CloudConfigurationManager.GetSetting("TokenCacheConnection")))
            });
````
````
public class RedisValidationResultCache : IValidationResultCache
    {
        private readonly ICache _cache;
	    private readonly IClock _clock;
	    private readonly int _cacheDuration;

        /// <summary>
        /// Initializes a new instance of the <see cref="InMemoryValidationResultCache"/> class.
        /// </summary>
        /// <param name="cacheDuration"></param>
        /// <param name="connection"></param>
        public RedisValidationResultCache(int cacheDuration, ConnectionMultiplexer connection)
            : this(cacheDuration, new TokenCacheClock(), new RedisTokenCache(connection))
	    { }

        /// <summary>
        /// Initializes a new instance of the <see cref="InMemoryValidationResultCache"/> class.
        /// </summary>
        /// <param name="cacheDuration"></param>
        /// <param name="clock">The clock.</param>
        /// <param name="cache">The cache.</param>
        /// <exception cref="System.ArgumentNullException">
        /// clock
        /// or
        /// options
        /// or
        /// cache
        /// </exception>
        private RedisValidationResultCache(int cacheDuration, IClock clock, ICache cache) 
		{
		    if (clock == null) { throw new ArgumentNullException("clock"); }
		    if (cache == null) { throw new ArgumentNullException("cache"); }
            if (cacheDuration <= 0) { throw new ArgumentNullException("cacheDuration"); }

            _cacheDuration = cacheDuration;
		    _cache = cache;
		    _clock = clock;
	    }

        /// <summary>
        /// Add a validation result
        /// </summary>
        /// <param name="token">The token.</param>
        /// <param name="claims">The claims.</param>
        /// <returns></returns>
	    public Task AddAsync(string token, IEnumerable<Claim> claims) 
        {
		    var expiryClaim = claims.FirstOrDefault(c => c.Type == ClaimTypes.Expiration);
		    var cacheExpirySetting = _clock.UtcNow.Add(TimeSpan.FromMinutes(_cacheDuration));
		    
            if (expiryClaim != null) {
			    long epoch;
			    if (long.TryParse(expiryClaim.Value, out epoch)) 
                {
				    var tokenExpiresAt = epoch.ToDateTimeOffsetFromEpoch();
				    
                    if (tokenExpiresAt < cacheExpirySetting) 
                    {
			            _cache.Add(token, claims, tokenExpiresAt);
			            return Task.FromResult<object>(null);
				    }
			    }
		    }
			
            _cache.Add(token, claims, cacheExpirySetting);

            return Task.FromResult<object>(null);
        }

        /// <summary>
        /// Retrieves a validation result
        /// </summary>
        /// <param name="token">The token.</param>
        /// <returns></returns>
        public Task<IEnumerable<Claim>> GetAsync(string token)
        {
            var result = _cache.Get(token);

            if (result != null)
            {
                return Task.FromResult(result as IEnumerable<Claim>);
            }

            return Task.FromResult<IEnumerable<Claim>>(null);
        }
    }
````

**Comment by leastprivilege** [comment]
I guess you need to debug that.

**Comment by jlegan** [comment]
Thanks @leastprivilege :). I will assume then there are not "gotchas" I should be aware of. Would you suggest grabbing the source for the middleware component as a starting point? I already have Idv3 outputting verbose trace and nothing is jumping out.

**Comment by leastprivilege** [comment]
You need the source code locally yes - either reference the source or point the debugger at the source while using the nuget.

**Comment by jlegan** [comment]
I found the defect but only after grabbing the source. It was an odd serialization bug that was being silently swallowed and then invoking the next middleware in the Owin pipeline but only when trying to retrieve from cache which is why the first succeeded and subsequent failed once cache was populated.

**Comment by OsmanMElsayed** [comment]
I'm encountering the same issue @jlegan, although I'm using the on-memory caching. I would be grateful if you can specify where is the "serialization bug" exactly.

**Comment by S3KCentrifugal** [comment]
Had the exact same issue, had nothing to do with a serialization bug. We arrived at a solution through a lot of trial and error. We actually don't know why this fixes the issue, hoping someone can shed some light on this.

**ValidationEndpointTokenProvider.cs**


                var cachedClaims = await _options.ValidationResultCache.GetAsync(tokenHash);
                if (cachedClaims != null)
                {
                    SetAuthenticationTicket(context, cachedClaims);

                    await Task.Delay(1); // Add this line 

                    return;
                }
            

Notice the await on Task.Delay for 1 millisecond. 

I know this may seem like an odd solution, but we have had 3 developers confirm the results in 4 different environments. Something we don't quite understand involving await/async is taking place.

We went from 100% fail rate, to 100% success rate on our API calls when using caching. Only the first WebAPI call would work due to it calling the TokenValidationEndpoint, all subsequent calls that used the cache failed to set claims on the Thread.CurrentPrincipal. With this one line of code the claims are populated every time.

It's a very kludgy solution, and the fact that we don't know why this fixes it is concerning.

**Comment by S3KCentrifugal** [comment]
I've solved the problem, and although it did turn out to be a fix to my code, there is still something odd happening within Asp.Net itself.

**Ok so first...** We were using Thread.CurrentPrincipal to access claims, when we should have been using RequestContext.Principal. They are always the same when we have EnableValidationResultCache = false. However they mismatch when we have EnableValidationResultCache = true. Easy solution, just stop using the Thread to access Principal.

**My current explanation...** Everything from middleware components, action filters and even the WebAPI action happens in the same execution flow. The RequestContext.Principal is set somewhere very early on. However Thread.CurrentPrincipal is being set outside of the execution flow, likely some kind of watcher thread somewhere keeping the Thread.CurrentPrincipal in sync with RequestContext. This may even be an Asp.Net(4.5.1) bug. 

In my experiments the time between setting the RequestContext.Principal and then synchronizing it with Thread.CurrentPrincipal is sub millisecond. In cases where claims are not available in the controller action method(Via the Thread) it is because the action method is being hit so quickly that the principal has not yet bet set to the thread. Which is why adding a Task.Delay(1) works. I can add this delay in the action method, action filters, or even the token provider and immediately the delay Thread.CurrentPrincipal is available.


**Conclusion...** This is all just observation though, it is still a large mystery how Asp.Net is assigning the Thread.CurrentPrincipal. In any case it seems fairly unreliable. As mentioned best solution is to just not use Thread.CurrentPrincipal and instead use RequestContext.Principal.

**Comment by leastprivilege** [comment]
Thread.CurrentPrincipal is a legacy mechanism. While it still works fine in MVC, it is not recommended anymore (due to inconsistencies as you found out) in Web API. 

In ASP.NET Core it is gone altogether.
