### ISSUE TITLE
Question: Is the signing certificate needs to be installed on the client application (RP) side

### ISSUE THREAD

**Issue by rklachko** [IdentityServer/Thinktecture.IdentityServer3#989]
I seem to be missing a part of the puzzle. When using implicit flow, the id_token is sent via a signed JWT (JWS). This token is signed using the signing certificate configured in IDS (e.g. idsrv3test.pfx in the samples). The JWS token header states the algorithm used to create the JWS signature, and a key parameter that should be used for token validation by the RP (As far as I could tell the IDS uses "x5t" - x.509 certificate thumbprint).
Assuming a web application client, does the RP needs this same certificate to be installed on his web server in order to perform the token validation? Otherwise how does it uses this "x5t" key to perform the token validation?

**Comment by loctanvo** [comment]
You only need the public key part of the certificate. You don't need to have it installed. When running the sample application, you can see the public key as `x5c` at the jwks endpoint `https://localhost:44333/core/.well-known/jwks`. You can manually validate the token by using a validation library. Otherwise, using e.g. MS OIDC middleware, it'll automatically discover the public key through the jwks endpoint and do the validation for you.

**Comment by rklachko** [comment]
Cool. I think the part I was missing was the jwks endpoint part (didn't appear on my fiddler :)
