### ISSUE TITLE
Scope and audience question

### ISSUE THREAD

**Issue by adestis-ds** [IdentityServer/Thinktecture.IdentityServer3#993]
Hi,

basic OIDC question: Let's assume I have a SPA using 2 WebAPI (api1, api2). The SPA (named WebA) gets at login time the IdToken +AccessToken from IdSrv. The SPA should use the IdToken for authentication and present the AccessToken to the api1 and api2. However the AccessToken has an audience of" http://[issuer]/resources" (where the IdToken has the correct "aud" of "WebA"). But shouldn't the api1 check the "aud" whether this is the token issued for api1 (and not api2). With the current behavior api2 could present an AccessToken to api1 and get data from there (which should not be allowed). Furthermore api1 has no role claims in the AccessToken in order to check if the client is e.g. allowed read or write access.

So what about presenting the IdToken to api1? Again the wrong audience ("WebA") but it has roles (good). But the scopes are missing... And to much information for the api (the api shouldn't be interested in the user profile...)

Q1: Should the SPA present the AccessToken or IdToken to api1/api2?

Q2: What field should the api1/api2 use to check if the token is for this api (aud or scope?).

Q3: If the SPA requesting tokens for 2 different apis (api1 and api2) how could it get 2 different tokens (either with different scopes or audiences) in a single request? (Keep in mind that api2 should not be allowed to use his own AccessToken to gather data from api2!)

Regards

Dirk

**Comment by brockallen** [comment]
1) ID tokens are meant for the client. Access tokens are meant for APIs. Don't send id tokens to APIs.

2) Technically both, but really scope

3) If the access token has both scopes, you only need one token. If you want them separate then those are two diff requests.

**Comment by adestis-ds** [comment]
If I send the AccessToken then the api has no idea what roles the user is in to (which renders the complete role management quite useless. So how can the api check whether the caller has read or write access or is allowed to access special resources? I assume one scope per api right? Or should the access rights within one api modeled with different scopes (multiple scopes per api)?

**Comment by brockallen** [comment]
You can put a user's claims in the access token. Look into scope claims. 

-Brock

**Comment by adestis-ds** [comment]
Ooops... DefaultClaimsProvider changed a lot during last months... I am still on an older version. Need to update and will check then again but by looking thru the code it seems possible... I'm still uncomfortable with the audience vs. scopes (because there seems to be no explicit rule what should be used) but your suggestion seems to be manageable and secure.

Thanks for the input!

**Comment by andreasgrimm** [comment]
@adestis-ds @brockallen regarding ...
> Q2: What field should the api1/api2 use to check if the token is for this api (aud or scope?)

I'd say as the issued `aud` claim usually contains the unique namespace of the protected resource endpoint - in your case e.g. `https://<yourdomain>/api1` or `https://<yourdomain>/api2/endpointname` - within the resource server code go and check `aud` for granting a client - e.g. `WebA` - access in the first place.

Then in addition do "client authorization" and grant potentially more granular client permissions by checking the `scope` claim value for the exact _access range_ of the access token that client `WebA` got issued. You can imagine a scope may contain e.g. `foo:read` and/or `foo:manage`. But maybe the resource owner did only consent to `foo:read` when first using `WebA` although the client requested also `foo:manage` and thus the access token's scope would contain only `foo:read`.

On top of that you may do _resource owner (user) authorization_ and grant potentially more granular resource owner permissions by checking e.g. the _custom_ `https://<yourdomain>/api1/roles` (or similar) claim value to personalize queried view data (`foo:read` is also required and kind of further differenciated/personalized) and to personalize managing tasks (`foo:manage` is also required, because although I might have the `Admin` role I didn't consent/allow this specific client `WebA` to do managing tasks but only a different client `NativeA`)
Or at authorization server level when customizing (role) claims you could decide to omit the `Admin` role for a specific (public or less trusted) client in general.

Do you see any problems with that approach?
